blank_issues_enabled: false
contact_links:
  - name: Questions, feedback, and discussions
    url: https://www.eksimracing.org/forum/index.php#c69
    about: "Please use our forum, it's the best place for discussions/report about OpenSR."
